# -*- coding: utf-8 -*-
"""Notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wnBPjLbEQLEiBqQxspT3A7LoasKOpfmC
"""

from datetime import datetime
import re

#define the note class
class Note:
  #initializing note attributes
    def __init__(self, memo, tags=None):
        self.memo = memo
        self.tags = tags if tags else []
        self.creation_date = datetime.now()


#define the notebook class to store the notes
class Notebook:
  #initializing notebook attributes
    def __init__(self):
        self.notes = []
        self.note_id = 1

 #this function is used to create a new note
    def create_new_note(self, memo, tags=None):
        new_note = Note(memo, tags)
        self.notes.append((self.note_id, new_note))
        self.note_id += 1

  #this function is used to search through existng notes
    def search_notes(self, query):
        results = []
        for note_id, note in self.notes:
          match = re.match(query,note.memo.lower())
          if query.lower() in note.memo.lower() or query.lower() in " ".join(note.tags) or match:
                results.append((note_id, note))
        return results

  #this function is used to modify existing notes
    def modify_note(self, note_id, memo, tags=None):
        for i, (existing_id, note) in enumerate(self.notes):
            if existing_id == note_id:
                self.notes[i] = (existing_id, Note(memo, tags))
                break

#menu class to store menu details
class Menu:
    def __init__(self):
        self.notebook = Notebook()

  #this function is used to display the menu to the user
    def display_menu(self):
        print("Menu:")
        print("1. Show Notes")
        print("2. Search Notes")
        print("3. Add Note")
        print("4. Modify Note")
        print("5. Quit")

  #this function is used to get input from the user
    def get_user_choice(self):
      try:
        choice = int(input("Enter your choice: "))
        return choice
      except ValueError as e:
        print()

  #this function is used to display exisitng notes to the user
    def show_notes(self):
        for note_id, note in self.notebook.notes:
            print("Note ID:", note_id)
            print("Memo:", note.memo)
            print("Tags:", note.tags)
            print("Creation Date:", note.creation_date)
            print()

  #this function is used to search through the note to find the required note
    def search_notes(self):
        query = input("Enter search query: ")
        results = self.notebook.search_notes(query)
        if results:
            print("Search Results:")
            for note_id, note in results:
                print("Note ID:", note_id)
                print("Memo:", note.memo)
                print("Tags:", note.tags)
                print("Creation Date:", note.creation_date)
                print()
        else:
            print("No matching notes found.")

  #this function is used to add a new note
    def add_note(self):
        memo = input("Enter memo: ")
        tags = input("Enter tags (comma-separated): ").split(',')
        self.notebook.create_new_note(memo, tags)
        print("Note added successfully.")


  #this function is used to modify existing notes
    def modify_note(self):
      try:
        note_id = int(input("Enter note ID to modify: "))
      except ValueError as e:
        print("please enter a valid note id")
      memo = input("Enter new memo: ")
      tags = input("Enter new tags (comma-separated): ").split(',')
      self.notebook.modify_note(note_id, memo, tags)
      print("Note modified successfully.")

#the main system where all the functions come together
def main():
    menu = Menu()
    while True:
        menu.display_menu()
        choice = menu.get_user_choice()
        if choice == 1:
            menu.show_notes()
        elif choice == 2:
            menu.search_notes()
        elif choice == 3:
            menu.add_note()
        elif choice == 4:
            menu.modify_note()
        elif choice == 5:
            print("Exiting...")
            break
        else:
            print("Invalid choice. Please choose again.")

if __name__ == "__main__":
    main()

